title: Trigger a particle system when your ball reaches the goal
hero_image: images/banner.png
description: Trigger a particle system when your ball reaches the goal
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Trigger a particle system when your ball reaches the goal
